animals = ['bear', 'ruby', 'peacock', 'kangaroo', 'whale', 'platypus']

puts "The animal at 1 is ruby"
puts "The third (3rd) animal is peacock"
puts "The first (1st) animal is bear"
puts "The animal at 3 is kangaroo"
puts "The fifth (5th) animal is whale"
puts "The animal at 2 is peacock"
puts "The sixth (6th) animal is platypus"
puts "The animal at 4 is whale"

puts "Now checking answers are correct through string interpolation: "
puts "The animal at 1 is #{animals[1]}"
puts "The third (3rd) animal is #{animals[2]}"
puts "The first (1st) animal is #{animals[0]}"
puts "The animal at 3 is #{animals[3]}"
puts "The fifth (5th) animal is #{animals[4]}"
puts "The animal at 2 is #{animals[2]}"
puts "The sixth (6th) animal is #{animals[5]}"
puts "The animal at 4 is #{animals[4]}"
